### ISSUE TITLE
Friendship does not reflect on both users

### ISSUE THREAD

**Issue by rvvergara** [btuerker/odin-facebook#4]
Hi, I found this issue while using the rails console.

1. I created two users `ryto` and `mike`.
2. I wanted them to be friends so I ran:
`ryto.friendships.create(user2_id: mike.id)`
3. Now I wanna prove that indeed `ryto` and `mike` are now friends:
 - running `Friendship.all` indeed shows the friendship between `ryto` and `mike`:
![image](https://user-images.githubusercontent.com/6015315/58142142-7f967f80-7c78-11e9-968c-77861caf69a2.png)

- checking for `ryto` 's friends to see if `mike`:
![image](https://user-images.githubusercontent.com/6015315/58142179-a48af280-7c78-11e9-8620-08cdaf83bd90.png)

Indeed `mike` is a good friend.
- However, checking if `ryto` appears in `mike` 's set of friends, this happens:
![image](https://user-images.githubusercontent.com/6015315/58142211-c4221b00-7c78-11e9-9577-c2adec32aeb1.png)

It shows an empty array.

What we want to do to make sure our controllers nor the views later on to bear the burden of computing `mike` 's friends, we wanna place such logic in the model for `user` and `friendship`.

**Comment by btuerker** [comment]
I handled mutual friendship relations in a bad way. It breaks database normalization rules by creating two rows for each friendship. Now, I changed all the relation logic in this [commit](https://github.com/btuerker/odin-facebook/pull/3/commits/d3ef1e8130ae0fefa5ea7fc1a4a9d2d7efdeb2a9). And added an instance method to User to get the related users(friends) through using union between direct and inverse friendships.
